-- 탐방로 시드 데이터 (Task 017).
-- supabase/seed/gen-trails.ts 로 국립공원공단 mountain.csv(로컬·CP949) 에서 생성.
-- (산, 코스명) 단위로 집약(courseID 세그먼트 중복 제거, 통제 우선순위: 상시>계절>개방).
-- status 는 nominal(계절 통제는 "closed" 저장) — 오늘 실효 상태는 Route(/api/trails)가
-- seasonal-closure.resolveTrailStatusOn 으로 closed_period 와 조회일 비교해 재계산한다.
-- id/mountain_id 는 uuid_generate_v5 로 계산(JS uuidv5 와 동일 = 재실행 멱등, Task 029 좌표 매칭).
-- 재생성: npx tsx supabase/seed/gen-trails.ts supabase/seed/trails.sql

create extension if not exists "uuid-ossp";

insert into public.trails (id, mountain_id, name, status, closed_reason, closed_period)
select
  uuid_generate_v5('6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'sangil:trail:' || v.slug || ':' || v.name),
  uuid_generate_v5('6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'sangil:' || v.slug),
  v.name, v.status, v.closed_reason, v.closed_period
from (values
  ('gyeryongsan', '수통골 2코스', 'open', null, null),
  ('gyeryongsan', '신원사 1코스', 'open', null, null),
  ('gyeryongsan', '수통골 1코스', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 8', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 9', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 10', 'open', null, null),
  ('gyeryongsan', '갑사 2코스', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 6', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 12', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 5', 'open', null, null),
  ('gyeryongsan', '갑사 1코스', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 7', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 11', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 1', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 4', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 3', 'open', null, null),
  ('gyeryongsan', '계룡산 탐방로 2', 'open', null, null),
  ('seoraksan', '곰배골입구~곰배령~강선리', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '오색약수터~망경대', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '주전골입구~오색흔들바위', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '용소폭포코스', 'open', null, null),
  ('seoraksan', '여심폭포입구~용소폭포', 'open', null, null),
  ('seoraksan', '마등령~한계령', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '남교리~대승령~한계령갈림길', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '대청봉코스', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '대청봉코스(백담)', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '황장폭포~장수대', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '오세암~봉정암', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '비선대~영시암', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '권금성코스', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('seoraksan', '비룡폭포코스', 'open', null, null),
  ('seoraksan', '울산바위코스', 'closed', '상시 통제', null),
  ('seoraksan', '백담사 코스', 'open', null, null),
  ('juwangsan', '주산지입구 ~ 주산지', 'open', null, null),
  ('juwangsan', '칼등고개 ~ 가메봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('juwangsan', '대전사 ~ 주봉 ~ 후리메기삼거리', 'open', null, null),
  ('juwangsan', '자하교 ~ 주왕암 ~ 학소교', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('juwangsan', '월외코스2', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('juwangsan', '청련사 ~ 대궐령 ~ 왕거암 ~ 먹구등 ~ 내기사', 'closed', '상시 통제', null),
  ('juwangsan', '제2폭포 ~ 가메봉 ~ 내원동 ~ 제3폭포', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('juwangsan', '절골입구 ~ 대문다리 ~ 가메봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('juwangsan', '대전사 ~ 장군봉 ~ 금은광이삼거리', 'open', null, null),
  ('juwangsan', '가메봉삼거리 ~ 왕거암', 'closed', '상시 통제', null),
  ('juwangsan', '금은광이정상 ~ 두수람 ~ 먹구등', 'closed', '상시 통제', null),
  ('juwangsan', '대둔산정상 ~ 두고개', 'closed', '상시 통제', null),
  ('juwangsan', '대둔산입구 ~ 태행산', 'closed', '상시 통제', null),
  ('juwangsan', '둔골 ~ 도토메기 ~ 월외폭포', 'closed', '상시 통제', null),
  ('sobaeksan', '묘적령 ~ 죽령', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('sobaeksan', '주정골 ~ 죽령(죽령옛길)', 'open', null, null),
  ('sobaeksan', '희방역 ~ 희방3주차장', 'open', null, null),
  ('sobaeksan', '버들밭 ~ 소야', 'open', null, null),
  ('sobaeksan', '희방주차장 ~ 연화봉', 'open', null, null),
  ('sobaeksan', '죽령 ~ 연화봉', 'open', null, null),
  ('sobaeksan', '삼가 ~ 비로봉', 'open', null, null),
  ('sobaeksan', '초암사 ~국망봉', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('sobaeksan', '달밭골 ~ 초암사', 'open', null, null),
  ('sobaeksan', '연화봉 ~ 비로봉', 'open', null, null),
  ('sobaeksan', '비로봉 ~ 국망봉', 'open', null, null),
  ('sobaeksan', '천동 ~ 천동삼거리', 'open', null, null),
  ('sobaeksan', '국망봉 ~ 늦은목이', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('sobaeksan', '하좌석 ~ 점마', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('sobaeksan', '어의곡 ~ 어의곡삼거리', 'open', null, null),
  ('sobaeksan', '을전 ~ 늦은맥이제', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('sobaeksan', '연화동 ~ 연화동삼거리', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('hallasan', '돈내코 탐방로', 'open', null, null),
  ('hallasan', '영실 탐방로', 'open', null, null),
  ('hallasan', '어리목 탐방로', 'open', null, null),
  ('hallasan', '성판악 탐방로', 'open', null, null),
  ('hallasan', '사라오름입구 ~ 사라오름', 'open', null, null),
  ('hallasan', '관음사 탐방로', 'open', null, null),
  ('hallasan', '어승생악 탐방로', 'open', null, null),
  ('hallasan', '석굴암 탐방로', 'open', null, null),
  ('jirisan', '유평 ~ 천왕봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '화엄사 ~ 무넹기', 'open', null, null),
  ('jirisan', '백무동 ~ 두지동', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '새재 ~ 삼거리', 'open', null, null),
  ('jirisan', '법계교 ~ 순두류 ~ 법계사', 'open', null, null),
  ('jirisan', '청학동 ~ 삼신봉 ~ 갈림길', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '노고단고개 ~ 천왕봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '의신마을 ~ 세석평전', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '백무동 ~ 세석평전', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '음정 ~ 벽소령', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '영원사 ~ 삼불사 ~ 약수암', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '의신 ~ 벽소령', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '범왕교 ~ 토끼봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '직전마을 ~ 피아골삼거리', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '성삼재 ~ 노고단정상', 'open', null, null),
  ('jirisan', '쟁기소 ~ 반야봉 ~ 삼도봉삼거리', 'closed', '상시 통제', null),
  ('jirisan', '와운교 ~ 요룡대', 'open', null, null),
  ('jirisan', '반선 ~ 화개재', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '만복대 ~ 성삼재', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '천은사입구 ~ 차나무밭', 'open', null, null),
  ('jirisan', '만복대 ~ 정령치 ~ 바래봉삼거리 ~ 운봉아래', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '대원교 ~ 숯가마터', 'open', null, null),
  ('jirisan', '육모정 ~ 약수터 ~ 육모정', 'open', null, null),
  ('jirisan', '뱀사골야영장 ~ 와운길', 'open', null, null),
  ('jirisan', '중산리탐방안내소 ~ 자연관찰로', 'open', null, null),
  ('jirisan', '정령치 ~ 정령치 습지', 'open', null, null),
  ('jirisan', '바래봉삼거리 ~ 바래봉', 'open', null, null),
  ('jirisan', '화엄사 ~ 연기암', 'open', null, null),
  ('jirisan', '구룡삼곡 ~ 구룡폭포', 'open', null, null),
  ('jirisan', '쌍계사 ~ 불일폭포 ~ 삼신봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '중산리 ~ 천왕봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '추성동 ~ 천왕봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '백무동 ~ 장터목', 'open', null, null),
  ('jirisan', '노루목 ~ 반야봉삼거리', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '신흥 ~ 의신옛길', 'open', null, null),
  ('jirisan', '부운마을 ~ 부운치1', 'open', null, null),
  ('jirisan', '칼바위 ~ 장터목', 'open', null, null),
  ('jirisan', '거림 ~ 1400고지', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '도마마을 ~ 삼불사', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '삼성궁입구 ~ 상불재', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '연하천삼거리 ~ 삼각고지', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '고기리 ~ 고리봉', 'open', null, null),
  ('jirisan', '전북학생교육원 ~ 세동치', 'open', null, null),
  ('jirisan', '팔랑마을 ~ 팔랑치', 'open', null, null),
  ('jirisan', '산덕임도 ~ 부운치2', 'open', null, null),
  ('jirisan', '월평마을 ~ 바래봉', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '구룡임도 ~ 구룡치', 'open', null, null),
  ('jirisan', '당동 ~ 당동고개', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '무넹기보 ~ 노고단고개', 'open', null, null),
  ('jirisan', '상위 ~ 묘봉치', 'closed', '산불방지 기간 통제', '2월 16일~4월 30일'),
  ('jirisan', '천은제입구 ~ 제방', 'open', null, null),
  ('songnisan', '자연학습원 ~ 가령산 ~ 낙영산', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '미타사 ~ 북가치 ~ 민판동', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '선유동 ~ 제비소', 'open', null, null),
  ('songnisan', '갈론 ~ 애기봉 ~ 옥녀봉 ~ 갈론', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '각연사삼거리 ~ 칠보산(하)', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '떡바위 ~ 칠보산 ~ 쌍곡폭포', 'open', null, null),
  ('songnisan', '각연사 ~ 칠보산', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '옥양폭포 ~ 백악산 ~ 수안재 ~ 입석', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '새목이 ~ 삼가리', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '비로산장 ~ 상고암', 'open', null, null),
  ('songnisan', '절말 ~ 쌍곡폭포 ~ 장성봉', 'open', null, null),
  ('songnisan', '소금강 ~ 군자산 ~ 도마골', 'open', null, null),
  ('songnisan', '세심정 ~ 도화리', 'open', null, null),
  ('songnisan', '천왕봉 ~ 형제봉', 'open', null, null),
  ('songnisan', '세심정 ~ 문장대', 'open', null, null),
  ('songnisan', '오송지구 ~ 문장대 ~ 북가치 ~ 묘봉', 'closed', '상시 통제', null),
  ('songnisan', '장각동 ~ 천왕봉 ~ 문장대', 'open', null, null),
  ('songnisan', '법주매표소 ~ 세심정 ~ 신선대', 'open', null, null),
  ('songnisan', '용화지구 ~ 매봉 ~ 묘봉 ~ 북가치 ~ 민판동', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('songnisan', '학소대 ~ 첨성대', 'open', null, null),
  ('songnisan', '사담리 ~ 낙영산 ~ 도명산', 'open', null, null),
  ('odaesan', '상원사 ~ 두로령', 'open', null, null),
  ('odaesan', '계방산 ~ 삼거리', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('odaesan', '운두령 ~ 계방산 ~ 노동계곡', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('odaesan', '북대사 ~ 상왕봉삼거리', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('odaesan', '상원사 ~ 내면 명계리', 'open', null, null),
  ('odaesan', '상원사 ~ 중대', 'open', null, null),
  ('odaesan', '동대산 ~ 두로령', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('odaesan', '소금강 ~ 동피골', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('odaesan', '월정사 회사거리 ~ 동피골 ~ 상원사', 'open', null, null),
  ('bukhansan', '우이분소 밑 ~ 구복암위 삼거리', 'open', null, null),
  ('bukhansan', '효자비 ~ 밤골능선삼거리', 'open', null, null),
  ('bukhansan', '비봉매표소 ~ 비봉능선 ~ 문수봉 ~ 대남문', 'open', null, null),
  ('bukhansan', '삼천사계곡 ~ 사모바위', 'open', null, null),
  ('bukhansan', '삼천사계곡입구 ~ 삼천사 ~ 부왕동암문', 'open', null, null),
  ('bukhansan', '산성분소 ~ 보리사', 'open', null, null),
  ('bukhansan', '북한산성입구 ~ 대서문 ~ 위문', 'open', null, null),
  ('bukhansan', '등운각 ~ 중성문 ~ 보국문', 'open', null, null),
  ('bukhansan', '북한산성계곡 ~ 대성암 ~ 대남문', 'open', null, null),
  ('dobongsan', '원각사입구 ~ 사패능선', 'open', null, null),
  ('dobongsan', '사패산 ~ 사패능선 ~ 포대능선', 'open', null, null),
  ('dobongsan', '송추 ~ 사패능선', 'open', null, null),
  ('dobongsan', '송추폭포입구 ~ 오봉능선', 'open', null, null),
  ('dobongsan', '송추 ~ 송추남능선 ~ 오봉능선 ~ 도봉주능선', 'open', null, null),
  ('dobongsan', '통일교 ~ 보문능선 ~ 우이암능선', 'open', null, null),
  ('dobongsan', '도봉서원 ~ 거북골 ~ 도봉주능선', 'open', null, null),
  ('dobongsan', '도봉서원 ~ 산정약수', 'open', null, null),
  ('bukhansan', '성불사입구 ~ 천진사', 'open', null, null),
  ('dobongsan', '덕제샘 ~ 망월사 ~ 포대능선', 'open', null, null),
  ('dobongsan', '원도봉 ~ 덕제샘 ~ 포대능선', 'open', null, null),
  ('dobongsan', '원도봉 ~ 다락능선 ~ 포대능선', 'open', null, null),
  ('dobongsan', '통일교 ~ 도봉대피소 ~ 다락능선', 'open', null, null),
  ('bukhansan', '석굴삼거리 ~ 신선대', 'open', null, null),
  ('bukhansan', '백운대매표소 ~ 하루재 ~ 위문 ~ 백운대', 'open', null, null),
  ('bukhansan', '백운매표소 ~ 깔닥고개', 'open', null, null),
  ('bukhansan', '정릉매표소 ~ 보국문', 'open', null, null),
  ('bukhansan', '백련사매표소 ~ 진달래능선 ~ 대동문', 'open', null, null),
  ('bukhansan', '용암문매표소 ~ 용암문', 'open', null, null),
  ('bukhansan', '선운교 ~ 옥류교 ~ 소귀천매표소 ~ 대동약수', 'open', null, null),
  ('bukhansan', '광륜사 ~ 은석암', 'open', null, null),
  ('dobongsan', '녹야원입구 ~ 다락능선', 'open', null, null),
  ('bukhansan', '성도원하단 ~ 마당바위', 'open', null, null),
  ('dobongsan', '성도원상단 ~ 관음암 ~ 도봉주능선', 'open', null, null),
  ('dobongsan', '도봉대피소 ~ 마당바위 ~ 주봉', 'open', null, null),
  ('dobongsan', '포대입구 ~ 도봉주능선 ~ 우이암', 'open', null, null),
  ('dobongsan', '무수골 ~ 원통사 ~ 우이암', 'open', null, null),
  ('dobongsan', '우이암매표소 ~ 원통사', 'open', null, null),
  ('bukhansan', '육모정매표소 ~ 육모정고개', 'open', null, null),
  ('dobongsan', '우이암 ~ 우이깔딱고개', 'open', null, null),
  ('bukhansan', '강북구 우이동 ~ 장흥면 교현리(우이령길)', 'open', null, null),
  ('bukhansan', '운가사매표소 ~ 진달래능선', 'open', null, null),
  ('bukhansan', '아카데미매표소 ~ 구천폭포 ~ 대동문', 'open', null, null),
  ('bukhansan', '위문 ~ 용암문 ~ 대동문 ~ 보국문 ~ 대성문 ~ 대남문', 'open', null, null),
  ('bukhansan', '냉골매표소 ~ 칼바위능선', 'open', null, null),
  ('bukhansan', '화계동매표소 ~ 칼바위능선', 'open', null, null),
  ('bukhansan', '빨래골매표소 ~ 정릉초교 ~ 산성주능선', 'open', null, null),
  ('bukhansan', '청수폭포 ~ 일선사 ~ 대성문', 'open', null, null),
  ('bukhansan', '북악매표소 ~ 형제봉삼거리', 'open', null, null),
  ('bukhansan', '형제봉매표소 ~ 형제봉 ~ 일선사', 'open', null, null),
  ('bukhansan', '평창1매표소 ~ 일선사 ~ 보현봉 ~ 대남문', 'open', null, null),
  ('bukhansan', '승가매표소 ~ 비봉능선', 'open', null, null),
  ('bukhansan', '탕춘대매표소 ~ 절터샘', 'open', null, null),
  ('bukhansan', '구기터널입구 ~ 구기불광능선', 'open', null, null),
  ('bukhansan', '정진 ~ 족두리봉', 'open', null, null),
  ('bukhansan', '불광계곡 ~ 비봉', 'open', null, null),
  ('bukhansan', '기자촌 ~ 향로봉', 'open', null, null),
  ('bukhansan', '진관계곡 ~ 비봉', 'open', null, null),
  ('bukhansan', '삼천사계곡 ~ 문수봉', 'open', null, null),
  ('bukhansan', '백화사입구 ~ 가사당암문', 'open', null, null),
  ('bukhansan', '용암사입구 ~ 의상능선 ~ 문수봉', 'open', null, null),
  ('bukhansan', '범용사입구 ~ 가사당암문', 'open', null, null),
  ('bukhansan', '행궁지입구 ~ 남장대지 ~ 청수동암문', 'open', null, null),
  ('bukhansan', '효자원 ~ 원효봉 ~ 대동사입구', 'open', null, null),
  ('bukhansan', '밤골입구 ~ 밤골계곡', 'open', null, null),
  ('bukhansan', '사기막골입구 ~ 백운대', 'open', null, null),
  ('bukhansan', '효자동 입구 ~ 솔고개', 'open', null, null),
  ('dobongsan', '오봉샘 ~ 오봉능선', 'open', null, null),
  ('bukhansan', '태고사 ~ 북한산대피소', 'open', null, null),
  ('dobongsan', '안골 ~ 사패산', 'open', null, null),
  ('bukhansan', '성불사입구 ~ 범골능선', 'open', null, null),
  ('bukhansan', '의정부시청뒤 ~ 백인굴', 'open', null, null),
  ('dobongsan', '범골 ~ 범골능선 ~ 사패능선', 'open', null, null),
  ('dobongsan', '회룡골 ~ 사패능선', 'open', null, null),
  ('bukhansan', '용학사 ~ 부왕동암문', 'open', null, null),
  ('bukhansan', '안말 ~ 체력단련장', 'open', null, null),
  ('dobongsan', '원도봉 ~ 체력단련장 ~ 포대능선', 'open', null, null),
  ('dobongsan', '다락원입구 ~ 다락능선', 'open', null, null),
  ('bukhansan', '독박골 ~ 구기불광능선', 'open', null, null),
  ('bukhansan', '수리봉계곡 입구 ~ 정진사 입구', 'open', null, null),
  ('dobongsan', '거북골 ~ 보문능선 ~ 도봉주능선', 'open', null, null),
  ('bukhansan', '삼천사하단 ~ 응봉능선 ~ 사모바위', 'open', null, null),
  ('bukhansan', '대호아파트 뒤 ~ 족두리봉', 'open', null, null),
  ('bukhansan', '선림 ~ 향림봉밑 갈림길', 'open', null, null),
  ('bukhansan', '원각사 입구 ~ 의정부시청 뒤', 'open', null, null),
  ('dobongsan', '시청IC ~ 원도봉입구', 'open', null, null),
  ('bukhansan', '구기계곡삼거리 ~ 승가사', 'open', null, null),
  ('bukhansan', '탕춘대매표소 ~ 암문', 'open', null, null),
  ('bukhansan', '불심원 뒤 ~ 구기터널 하단', 'open', null, null),
  ('dobongsan', '의정부시·도봉구경계 ~ 강북·도봉구 경계', 'open', null, null),
  ('bukhansan', '독박골 ~ 족두리봉 밑 갈림길', 'open', null, null),
  ('dobongsan', '오봉능선 ~ 도봉주능선', 'open', null, null),
  ('bukhansan', '효자비 ~ 북문', 'open', null, null),
  ('bukhansan', '헤원사삼거리 ~ 구기분소', 'open', null, null),
  ('bukhansan', '구기분소 ~ 대남문', 'open', null, null),
  ('dobongsan', '송추IC ~ 오봉탐방지원센터', 'open', null, null),
  ('wolchulsan', '천황사지구 ~ 도갑사', 'open', null, null),
  ('wolchulsan', '천황사 ~ 통천문삼거리', 'open', null, null),
  ('wolchulsan', '죽정 ~ 월대암', 'open', null, null),
  ('wolchulsan', '구정봉 ~ 홍계골', 'open', null, null),
  ('wolchulsan', '금릉경포대 ~ 바람재', 'open', null, null),
  ('wolchulsan', '경포대삼거리 ~ 종주능선', 'open', null, null),
  ('wolchulsan', '천황주차장 ~ 탑동약수터', 'open', null, null),
  ('wolchulsan', '하치마을 ~ 사자저수지', 'open', null, null),
  ('naejangsan', '입암산코스', 'open', null, null),
  ('naejangsan', '신선봉코스', 'open', null, null),
  ('naejangsan', '서래봉코스', 'open', null, null),
  ('naejangsan', '운문암갈림길~옹달샘갈림길', 'open', null, null),
  ('naejangsan', '등천리~은선동', 'open', null, null),
  ('naejangsan', '대가~신선봉', 'open', null, null),
  ('naejangsan', '만화재~북문', 'open', null, null),
  ('naejangsan', '장성새재코스', 'open', null, null),
  ('naejangsan', '제5주차장~서래약수', 'open', null, null),
  ('naejangsan', '구암사입구~백양계곡', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('naejangsan', '장성새재 ~ 상왕봉', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('naejangsan', '내장사~연자봉', 'open', null, null),
  ('naejangsan', '백양사~내장사종주코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('naejangsan', '일주문 ~ 내장사', 'open', null, null),
  ('naejangsan', '능선일주코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('naejangsan', '백양사종주코스', 'open', null, null),
  ('naejangsan', '몽계폭포~백양사코스', 'open', null, null),
  ('gayasan', '남산제일봉1코스', 'open', null, null),
  ('gayasan', '가야산3코스', 'open', null, null),
  ('gayasan', '가야산2코스', 'open', null, null),
  ('gayasan', '가야산소리길', 'open', null, null),
  ('gayasan', '만물상코스', 'open', null, null),
  ('gayasan', '남산제일봉2코스', 'open', null, null),
  ('gayasan', '가야산1코스', 'open', null, null),
  ('deogyusan', '육십령~남덕유산', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '인월담~향적봉', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '양악~월성재', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '병곡~동엽령', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '신풍령코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '치목코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '서창코스', 'open', null, null),
  ('deogyusan', '종주코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '삿갓골재코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '월성재코스', 'open', null, null),
  ('deogyusan', '오수자굴코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '횡경재코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('deogyusan', '동엽령코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('chiaksan', '영원산성~주능선', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '구룡탐방지원센터~성남탐방지원센터코스', 'open', null, null),
  ('chiaksan', '슥새울입구~슥새울', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '수레너미~한다리골', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '부곡탐방지원센터~비로봉코스', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '부곡 큰무레골~비로봉', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '곧은재지킴터~곧은재', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '황골탐방지원센터~비로봉코스', 'open', null, null),
  ('chiaksan', '행구동탐방지원센터~향로봉코스', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('chiaksan', '금대분소~남대봉코스', 'open', null, null),
  ('chiaksan', '세렴폭포~비로삼거리', 'open', null, null),
  ('woraksan', '금수산코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('woraksan', '구담봉코스', 'open', null, null),
  ('woraksan', '영봉코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('woraksan', '마패봉코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('woraksan', '만수봉코스', 'open', null, null),
  ('woraksan', '백두대간코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('woraksan', '하늘재역사관찰로', 'open', null, null),
  ('woraksan', '북바위산코스', 'open', null, null),
  ('woraksan', '가은산코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일'),
  ('woraksan', '제비봉코스', 'open', null, null),
  ('woraksan', '도락산코스', 'open', null, null),
  ('seoraksan', '소공원~희운각대피소', 'closed', '산불방지 기간 통제', '3월 4일~5월 15일'),
  ('woraksan', '포암산코스', 'closed', '산불방지 기간 통제', '3월 1일~4월 30일')
) as v(slug, name, status, closed_reason, closed_period)
on conflict (id) do update set
  mountain_id = excluded.mountain_id,
  name = excluded.name,
  status = excluded.status,
  closed_reason = excluded.closed_reason,
  closed_period = excluded.closed_period;
